### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 37632 values, but the requested shape has 49152

### ISSUE THREAD

**Issue by abdou31** [yinguobing/cnn-facial-landmark#48]
Hello Sir,
I tried to train my own dataset for eyes detection , i have created my dataset with pts files and i have annoteted the dataset by generating .json file from pts files that i have created .
The number of points for eyes dataset is 80 ( both x and y coordinates ), after executing pts_tools.py ,  extract_face_from_ibug.py and generate_record.py .
I start the train by executing:
> python3 landmark.py

Note : i changed the number of logits from 136 to 80 
I get this error : 
> tensorflow.python.framework.errors_impl.InvalidArgumentError: Input to reshape is a tensor with 37632 values, but the requested shape has 49152
         [[{{node Reshape}}]]
         [[node IteratorGetNext (defined at landmark.py:249) ]]
         [[node IteratorGetNext (defined at landmark.py:249) ]]

I think that the error comes from extrac_face_from_ibug.py , in effect , Target_size in this file is 112 
So :
> 112 * 112 * 3=37632
>128 * 128 * 3=49152

I changed 128 by 112 in landmark.py , 
the training work now but i don't know that is a solution or no , also it can't be started with pre-trained model , 
Did you have any idea how to solve this?
Thanks

**Comment by yinguobing** [comment]
@abdou31 You are right about the size. 
In the `landmark` module, the input images are expected to be in shape of `IMG_HEIGHT, IMG_WIDTH, IMG_CHANNEL` (see code [here](https://github.com/yinguobing/cnn-facial-landmark/blob/e5779e11d8fecac60ca30cc72db893d1ec64eacb/landmark.py#L218)). Keep these value consistent with the dataset used for training.

Another way to solve this issue is to use image resizing in the input function. Be careful with this as transformation of image may result in mismatching with the labels. Check them before using.

**Comment by abdou31** [comment]
Can you explain me what should i change for now ?
did you mean that i keep the value to 128 for `IMG_HEIGHT `and for `IMG_WIDTH` in landmark.py?

**Comment by yinguobing** [comment]
both 128 and 112 are fine, as long as it is consistent with the data used for training.

**Comment by abdou31** [comment]
what if i keep 128 or increase the value for exemple 256 and changing this value for pts_tools and extract_face_from_ibug and repeat the process ( execute pts_tools and extract_face_from_ibug)? 
another question , How can i reduce the size of the landmark?

**Comment by abdou31** [comment]
Why you closed the issue?
You didn't give me an answer.
